# Generated by Django 4.1.5 on 2023-03-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='caricatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrec', models.CharField(max_length=45)),
                ('genero', models.CharField(max_length=45)),
                ('fecha_compra', models.DateField()),
                ('codigov', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=45)),
                ('pais', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('fecha_registro', models.DateField()),
            ],
        ),
    ]
